# Generated by Django 3.1.2 on 2021-01-21 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0002_profile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmi',
            field=models.FloatField(default=22.05),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 20, 16, 39, 747290)),
        ),
    ]
